osce_appname: 'oso-console-extensions'

# osce_target will be one of 'free|paid|dedicated'.
# osod_cluster_tier ==> osce_target
#           starter ==> free
#               pro ==> paid 
#             dsaas ==> free
#              osio ==> free
#         dedicated ==> dedicated

# WARNING: Keep these in sync with the defaults in the template.  We want the
# template to be independently usable so default must be defined in both.
osce_git_repo: 'https://github.com/openshift/online-console-extensions.git'
osce_git_ref: 'master'

# Location on master where we store OpenShift app template
osce_template_path: /etc/openshift-online/templates/console-extensions-template.yml
osce_namespace: 'openshift-infra'

osce_webconsole_config: 'webconsole-config'
osce_webconsole_namespace: 'openshift-web-console'

# If true, will uninstall all app components before running rest of role
osce_uninstall: False

# These variables must be defined before role execution
required_vars:
  - osce_target
  - osce_stylesheets
  - osce_scripts
  - osce_properties
  - osce_url

osce_builder_image: 'registry.reg-aws.openshift.com/openshift3/{{ osce_appname }}-builder:latest'
